controllers/book_control.py
#!/usr/bin/python3
# -*- encoding: utf-8 -*-

from controllers.main import *
from models.book_model import Book, Author, Year
from sqlalchemy import desc
from configs.fileserver_config import *
from werkzeug.utils import secure_filename
from pypinyin import lazy_pinyin
from utils import *
import os
import time


def init_book_db():
    # book1 = Book(title='平凡的世界')
    # book2 = Book(title='人生')
    # book3 = Book(title='活着')
    # book4 = Book(title='大江大河')
    # book5 = Book(title='百年孤独')
    bookReading1 = Book(title='侯卫东官场笔记')
    bookReading2 = Book(title='激荡三十年')

    # author1 = Author(name="路遥", state="中")
    # author2 = Author(name="余华", state="中")
    # author3 = Author(name="宋运辉", state="中")
    # author4 = Author(name="加西亚.马尔克斯", state="哥")
    authorRead1 = Author(name="侯卫东", state="中")
    authorRead2 = Author(name="吴晓波", state="中")

    # year1 = Year(year=2016)
    # year2 = Year(year=2018)
    # year3 = Year()
    yearRead = Year(year=9999)

    # book1.author = author1
    # book1.year = year1
    # book2.author = author1
    # book2.year = year1
    # book3.author = author2
    # book3.year = year1
    # book4.author = author3
    # book4.year = year3
    # book5.author = author4
    # book5.year = year2

    bookReading1.author = authorRead1
    bookReading1.year = yearRead
    bookReading2.author = authorRead2
    bookReading2.year = yearRead

    db.session.add_all([bookReading1, bookReading2])
    db.session.add_all([authorRead1, authorRead2])
    db.session.add_all([yearRead])
    db.session.commit()


@main.route('/reading/')
def reading():
    # init_book_db()
    return redirect(url_for('main.reading_cat', year=9999))


@main.route('/reading/<year>/')
def reading_cat(year):
    year_all = Year.query.filter().order_by(desc(Year.year)).all()
    year = Year.query.filter(Year.year == int(year)).first()

    dicts = {
        'year_all': year_all,
        'activeYear': year
    }

    return render_template('reading.html', **dicts)


@main.route('/book/<year_id>/<book_id>')
def book_detail(year_id, book_id):
    year_all = Year.query.filter().order_by(desc(Year.year)).all()
    year = Year.query.filter(Year.year == int(year_id)).first()
    book = Book.query.filter(Book.id == int(book_id)).first()

    if book.mdNotePath:
        path = str(book.mdNotePath)
        md_data = sec_readfile(path)
    else:
        md_data = '## 该文档不存在！'

    dicts = {
        'year_all': year_all,
        'activeYear': year,
        'title': book.title,
        'md_data': md_data
    }
    return render_template('book/book_detail.html', **dicts)


@main.route('/book/create/<year_id>', methods=['GET', 'POST'])
def create_book(year_id):
    if request.method == 'GET':
        year_all = Year.query.filter().order_by(desc(Year.year)).all()
        year = Year.query.filter(Year.year == int(year_id)).first()

        dicts = {
            'year_all': year_all,
            'activeYear': year
        }
        return render_template('book/create_book.html', **dicts)
    else:
        book_title = request.form.get('bookTitle')
        if book_title:
            new_book = Book(title=book_title)

            book_desc = request.form.get('bookTitleDesc')
            if book_desc:
                new_book.title_desc = book_desc

            author = request.form.get('bookAuthor')
            author_state = request.form.get('bookAuthorState')
            book_author = Author(name=author, state=author_state)
            new_book.author = book_author

            book_year = Year.query.filter(Year.year == int(year_id)).first()
            if not book_year:
                book_year = Year(year=int(year_id))
                db.session.add(book_year)
            new_book.year = book_year

            book_image = request.form.get('bookImgLink')
            if book_image:
                new_book.imagePath = book_image

            oneSentence = request.form.get('bookOneSentence')
            if oneSentence:
                new_book.one_sentence = oneSentence

            eBookPath = request.form.get('eBookPath')
            if eBookPath:
                new_book.eBookPath = eBookPath

            new_book.finish_date = str(time.strftime("%Y-%m-%d"))

            # 记录读后感
            content = request.form.get('docContent')
            if content:
                path = FILESERVER + PATHSEP + 'reading' + PATHSEP + year_id + PATHSEP
                full_filename = path + secure_filename(''.join(lazy_pinyin(book_title))) + '.md'
                if not os.path.exists(path):
                    os.makedirs(path)
                sec_writefile(full_filename, content)
                new_book.mdNotePath = full_filename

            # 更新数据库
            db.session.add(book_author)
            db.session.add(new_book)
            db.session.commit()

        return redirect(url_for('main.reading_cat', year=year_id))


@main.route('/edit_book/<year_id>/<book_id>', methods=['GET', 'POST'])
def edit_book(year_id, book_id):
    book_local = Book.query.filter(Book.id == int(book_id)).first()
    modify_flag = False

    if request.method == 'GET':
        year_all = Year.query.filter().order_by(desc(Year.year)).all()
        year = Year.query.filter(Year.year == int(year_id)).first()

        note_content = ""
        if book_local.mdNotePath:
            path = str(book_local.mdNotePath)
            note_content = sec_readfile(path)

        dicts = {
            'year_all': year_all,
            'activeYear': year,
            'book': book_local,
            'noteContent': note_content
        }
        return render_template('book/edit_book.html', **dicts)
    else:
        if request.form.get("newTitle"):
            new_title = request.form.get("newTitle")
            book_local.title = new_title
            modify_flag = True

        if request.form.get("newImgLink"):
            new_imageUrl = request.form.get("newImgLink")
            book_local.imagePath = new_imageUrl
            modify_flag = True

        if request.form.get('updateContent'):
            updateContent = request.form.get('updateContent')
            sec_fn = secure_filename(''.join(lazy_pinyin(book_local.title))) + '.md'
            full_filename = FILESERVER + PATHSEP + 'reading' + PATHSEP + year_id + PATHSEP + sec_fn

            if not os.path.exists(full_filename):
                if book_local.mdNotePath:
                    try:
                        os.remove(book_local.mdNotePath)
                    except OSError:
                        pass

            dir_path = os.path.dirname(full_filename)
            if not os.path.exists(dir_path):
                os.makedirs(dir_path)

            book_local.mdNotePath = full_filename
            sec_writefile(full_filename, updateContent)
            modify_flag = True

        # 更新数据库表
        if modify_flag:
            db.session.commit()

        return redirect(url_for('main.reading_cat', year=year_id))

controllers/file_server.py
#!/usr/bin/python3
# -*- encoding: utf-8 -*-

from controllers.main import *
from configs.fileserver_config import *
import os
import time
from flask import make_response, send_from_directory
from xml.dom import minidom

FILE_DIR = os.path.join(FILESERVER, 'guides')


@main.route('/download/<fullname>')
def downloader(fullname):
    filename = fullname.split(os.sep)[-1]
    dirpath = fullname[:-len(filename)]
    print(fullname)
    print(dirpath)
    print(filename)
    return send_from_directory(dirpath, filename, as_attachment=True)


@main.route('/doc/')
@main.route('/doc/<subdir>')
def document(subdir=None):
    if not subdir:
        # 名字为空，切换到根目录
        os.chdir(FILE_DIR)
        subdir = ''
    else:
        # fullname = os.path.join(FILE_DIR, subdir)
        fullname = FILE_DIR + os.sep + subdir
        # if fullname.endswith(os.sep):
        #     fullname = fullname[:-1]

        #  如果是文件，则下载
        if os.path.isfile(fullname):
            return redirect(url_for('main.downloader', fullname=fullname))
        #  如果是目录，切换到该目录下面
        else:
            os.chdir(fullname)

    current_dir = os.getcwd()
    current_list = os.listdir(current_dir)
    contents = []
    for i in sorted(current_list):
        fullpath = current_dir + os.sep + i
        # 如果是目录，在后面添加一个sep
        if os.path.isdir(fullpath):
            extra = os.sep
        else:
            extra = ''
        content = dict()
        content['filename'] = i + extra
        content['mtime'] = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(os.stat(fullpath).st_mtime))
        content['size'] = str(round(os.path.getsize(fullpath) / 1024)) + 'k'
        contents.append(content)
    return render_template('webtools/file_server.html', contents=contents, subdir=subdir, ossep=os.sep)


@main.route('/download/file/')
def file_downloader():
    file_path = FILE_DIR
    filename = "test.xml"

    xml = minidom.Document()
    root = xml.createElement('rpm_delta')

    package_name_delta = xml.createElement('package_name_delta')
    rpm = xml.createElement('rpm')
    rpm.setAttribute('name', 'dophi-ldc-devel')
    package_name_delta.appendChild(rpm)

    package_file_delta = xml.createElement('package_file_delta')
    rpm = xml.createElement('rpm')
    rpm.setAttribute('name', 'c-ares')
    minus_filelist = xml.createElement('minus_filelist')
    file = xml.createElement('file')
    file.setAttribute('name', "usr/bin/adig")
    reason = xml.createElement('reason')
    file.appendChild(reason)
    minus_filelist.appendChild(file)
    rpm.appendChild(minus_filelist)
    package_file_delta.appendChild(rpm)

    root.appendChild(package_name_delta)
    root.appendChild(package_file_delta)

    # print(root.toprettyxml(indent='\t'))

    os.chdir(file_path)
    if os.path.exists(filename):
        os.remove(filename)
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(root.toprettyxml(indent='\t'))

    response = make_response(
        send_from_directory(file_path, filename.encode('utf-8').decode('utf-8'), as_attachment=True))
    response.headers["Content-Disposition"] = "attachment; filename={}".format(filename.encode().decode('latin-1'))
    return response


def xml2string(path):
    result = ''
    with open(path, 'r') as f:
        for line in f.readlines():
            line = line.strip()
            result += line
    return result


@main.route('/xml/editor/')
def xml_editor():
    xml_path = os.path.join(FILE_DIR, "delta.xml")
    xml_string = xml2string(xml_path)
    return render_template('webtools/xml_editor.html', xml=xml_string)

controllers/games.py
#!/usr/bin/python3
# -*- encoding: utf-8 -*-

from controllers.main import *
from configs.fileserver_config import *
import os, ast

game_dict = dict()


def read_game_info():
    game_info_path = os.path.join(FILESERVER, 'games', 'game_infos.js')
    with open(game_info_path, 'r', encoding='utf-8') as f:
        game_infos = f.read()
    global game_dict
    game_dict = ast.literal_eval(game_infos)


@main.route('/games/')
def playground():
    if len(game_dict) == 0:
        read_game_info()
    return render_template('games/game_home.html', games=game_dict)


@main.route('/game/<name>/')
def game(name):
    if len(game_dict) == 0:
        read_game_info()
    real_title = game_dict[name]['title']
    real_name = game_dict[name]['name']
    return render_template('games/game.html', title=real_title, name=real_name)


@main.route("/datalake/statistic")
def datalake_statistic():
    data = {
        "组织域": ['url1', 'url2'],
        "归档域": ['url1', 'url2'],
        "开发域": 'NA',
        "构建域": 'NA',
        "需求域": 'NA',
        "测试域": 'NA',
        "设计域": 'NA'
    }

    links = {
        "天眼": "god-eye.data.com",
        "云杉搜索": "yunshan.rnd.huawei.com"
    }

    return render_template('datalake/statistic.html', data=data, links=links)

controllers/main.py
#!/usr/bin/python3
# -*- encoding: utf-8 -*-

from flask import Blueprint, render_template, request, session, redirect, url_for
from flask import jsonify, Response, send_from_directory
from models.user_model import db, User
from sqlalchemy import and_

main = Blueprint('main', __name__)


@main.route('/')
def index():
    # return redirect(url_for('main.reading'))
    return redirect(url_for('main.blogs_record'))
    # return redirect(url_for('main.poetry'))
    # return redirect(url_for('main.notes_record'))


@main.route('/login/', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('login.html')
    else:
        username = request.form.get('username')
        password = request.form.get('password')
        checkbox = request.form.get('checkbox')

        user = User.query.filter(and_(User.username == username,
                                      User.password == password)).first()
        if user:
            session['username'] = username
            if checkbox:
                session.permanent = True
                print('[Info] set session permanent = true!')
            return redirect(url_for('main.index'))
        else:
            print('[Info] 用户名或密码错误！')
            return redirect(url_for('main.login'))


@main.route('/logout/')
def logout():
    if session.get('username'):
        session.pop('username')
    return redirect(url_for('main.index'))


@main.route('/register/', methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template('register.html')
    else:
        username = request.form.get('username')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter(User.username == username).first()

        if user:
            return '用户已存在！请重新注册！'
        else:
            if password1 != password2:
                return '两次密码输入不一致，请确认后再重新注册！'
            else:
                session['username'] = username
                user = User(username=username, password=password1)
                db.session.add(user)
                db.session.commit()
                return redirect(url_for('main.index'))


# TODO: 使用 全局 g 对象 (其实这里的g对象 只是一个单次请求的全局变量，而非多次请求)
# TODO: 向全局传递 selected_navbar, years, poetry_categories 信息
# TODO: 使用 上下文处理器 (context_processor) 设置真正的全局统一环境变量 (global)
# TODO: 替代方案：使用 session (不推荐)！

@main.context_processor
def set_context():
    username = session.get('username')
    if username:
        user = User.query.filter(User.username == username).first()
        dicts = {
            'username': user.username,
            'authority': user.authority
        }
        return dicts
    else:
        return {}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    <!-- FontAwesome5.9 CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='fontawesome/css/font-awesome.min.css') }}">
    <!-- Bootstrap3.7 CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap/css/bootstrap.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='user-defined/css/base.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap/css/bootstrap-table.min.css') }}">
    <!-- Start Bootstrap Admin -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='sb-admin-2/css/sb-admin-2.min.css') }}">

    <!-- MetisMenu CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='metisMenu/metisMenu.min.css') }}" rel="stylesheet">

    <!-- EditorMd CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='editormd/css/editormd.css') }}" />
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='editormd/css/editormd.preview.css') }}" />

	{% block link %}{% endblock %}

</head>
<body>
<div id="wrapper">
	
	<!-- Bootstrap3 导航条 -->
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Objective Management · OKR</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav nav-tabs navbar-left">
                    <li class="nav-item mainNavLi mainNavLiReading">
                        <a class="nav-link" href="{{ url_for('main.reading') }}">阅 读<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item mainNavLi mainNavLiAnalysis">
                        <a class="nav-link" href="{{ url_for('main.tushare_quant') }}" target="_blank">量化分析</a>
                    </li>
                    <li class="nav-item mainNavLi mainNavLiBlogs">
                        <a class="nav-link" href="{{ url_for('main.blogs_record') }}">博 客</a>
                    </li>
                    {% if session.get('username') and authority == "Root" %}
                    <li class="nav-item mainNavLi mainNavLiNotes">
                        <a class="nav-link" href="{{ url_for('main.notes_record') }}">笔 记</a>
                    </li>
                    {% endif %}
                    <li class="nav-item mainNavLi mainNavLiPoetry">
                        <a class="nav-link" href="{{ url_for('main.poetry') }}">诗 歌</a>
                    </li>
                    <li class="nav-item mainNavLi mainNavLiFiles">
                        <a class="nav-link" href="{{ url_for('main.document') }}">文件区</a>
                    </li>
                    <li class="nav-item mainNavLi mainNavLiGames">
                        <a class="nav-link" href="{{ url_for('main.playground') }}">娱乐圈</a>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li class="nav-item">
                        <a href="https://zhchuch.github.io/" target="_blank">Homepage</a>
                    </li>
                    {% if session.get('username') %}
                        <li class="nav-item">
                            <a href="#" class="nav-link">{{ session.get('username') }}</a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ url_for('main.logout') }}" class="nav-link">注销</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.login') }}">登录</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.register') }}">注册</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">

                <li class="sidebar-search">
                    <div class="input-group custom-search-form">
                        <input type="text" class="form-control" placeholder="Search">
                        <span class="input-group-btn">
                        <button class="btn btn-default" type="button">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                    </div>
                    <!-- /input-group -->
                </li>

                {% block sidebar %}{% endblock %}
            </ul>
        </div>
    </div>

    <div id="page-wrapper">
        <div class="content">
            {% block content %}{% endblock %}
        </div>
    </div>

</div>

<script src="{{ url_for('static', filename='jquery/jquery-3.4.1.min.js') }}" type="text/javascript"></script>
<script src="{{ url_for('static', filename='d3/d3.min.js') }}" type="text/javascript"></script>
<script src="{{ url_for('static', filename='popperjs/umd/popper.min.js') }}" type="text/javascript"></script>
<!-- Bootstrap3.7 JS -->
<script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}" type="text/javascript"></script>
<script src="{{ url_for('static', filename='bootstrap/js/bootstrap-table.min.js') }}" type="text/javascript"></script>

<!-- Start Bootstrap Admin -->
<script src="{{ url_for('static', filename='sb-admin-2/js/sb-admin-2.min.js') }}" type="text/javascript"></script>

<!-- Metis Menu Plugin JavaScript -->
<script src="{{ url_for('static', filename='metisMenu/metisMenu.min.js') }}" type="text/javascript"></script>

<script src="{{ url_for('static', filename='user-defined/js/base.js') }}" type="text/javascript"></script>

<script src="{{ url_for('static', filename='editormd/editormd.min.js') }}" type="text/javascript"></script>
<script src="{{ url_for('static', filename='user-defined/js/uploadfile.js') }}" type="text/javascript"></script>
<script type="text/javascript">
    var sidebar = document.getElementsByClassName("sidebar")[0];

    $(function() {
        var editor = editormd("my-editor-md", {
            width  : "100%",
            height : 650,
            path   : "/static/editormd/lib/",
            tex              : true,
            tocm             : true,
            emoji            : true,
            taskList         : true,
            codeFold         : true,
            searchReplace    : true,
            htmlDecode       : "style,script,iframe",
            flowChart        : true,
            sequenceDiagram  : true,
            imageUpload      : true,
            imageFormats     :["jpg", "jpeg", "png", "bmp", "webp"],
            imageUploadURL   : {{ url_for('main.upload') }},
            onload:function(){
                initPasteDragImg(this)
            },
            onfullscreen : function() {
                //alert("onfullscreen");
                sidebar.style.display = "none";
            },
            onfullscreenExit : function () {
                sidebar.style.display = "";
            }
        });
    });
</script>

<!-- EditorMd Preview JS -->
<script src="{{ url_for('static', filename='editormd/lib/marked.min.js') }}"></script>
<script src="{{ url_for('static', filename='editormd/lib/prettify.min.js') }}"></script>
<script src="{{ url_for('static', filename='editormd/lib/raphael.min.js') }}"></script>
<script src="{{ url_for('static', filename='editormd/lib/underscore.min.js') }}"></script>
<script src="{{ url_for('static', filename='editormd/lib/sequence-diagram.min.js') }}"></script>
<script src="{{ url_for('static', filename='editormd/lib/flowchart.min.js') }}"></script>
<script src="{{ url_for('static', filename='editormd/lib/jquery.flowchart.min.js') }}"></script>
<script src="{{ url_for('static', filename='editormd/editormd.min.js') }}"></script>
<script type="text/javascript">
    var testEditor;
    $(function () {
        testEditor = editormd.markdownToHTML("doc-content", {
            htmlDecode: "style,script,iframe",
            emoji: true,
            taskList: true,
            tex: true,
            flowChart: true,
            sequenceDiagram: true,
            codeFold: true,
            tocm: true,
            searchReplace: true,
    });});
</script>

{% block jsscript %}{% endblock %}

</body>
</html>

templates/login.html
{% extends 'base.html' %}

{% block title %}登录{% endblock %}

{% block content %}
<div class="form-container">
	<h3 style="text-align: center;">登录</h3>
	<form class="form-content" action="" method="POST">
		<div class="form-group required">
			<label for="telephone" class="star-label">用户名</label>
			<input type="text" id="telephone" class="form-control" name="username" placeholder="Username" required="required">
		</div>
		<div class="form-group required">
			<label for="password" class="star-label">密码</label>
			<input type="password" id="password" class="form-control" name="password" placeholder="Password" required="required">
		</div>
		<div class="form-check">
			<input type="checkbox" id="inputCheck" class="form-check-input" name="checkbox">
			<label class="form-check-label" for="inputCheck">记住我</label>
		</div>
		<div class="form-group">
			<button type="submit" class="btn btn-primary btn-block">立即登录</button>
		</div>
	</form>
</div>
{% endblock %}

{% block jsscript %}
    <script type="text/javascript">
        var content = document.getElementsByClassName("content")[0];
        content.style.setProperty("width", "800px");
    </script>
{% endblock %}

templates/reading.html
{% extends 'base.html' %}

{% block title %}阅读{% endblock %}

{% block link %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='user-defined/css/reading.css') }}">
{% endblock %}

{% block sidebar %}
    {% for year in year_all %}
        <li>
            <a href="{{ url_for('main.reading_cat', year=year.year) }}" class="navBookYear{{ year.year }}"><i class="fa fa-fw fa-book"></i>
        {%- if year.year == 9999 -%}
            Reading
        {%- else -%}
            {{ year.year }}
        {%- endif -%}
        </a></li>
    {% endfor %}
{% endblock %}

{% block content %}
<div class="page-content">
    <script>
        var activeYear = "{{ activeYear.year }}";
    </script>
<ol>
	<table>
        {%- set books = activeYear.books -%}
        {%- set plusTDNum = (4 - (books|length % 4)) % 4 -%}
        {%- for book in books -%}
            {% if loop.index0 % 4 == 0 %}
            <tr>
            {%- endif -%}
            {%- if book.display == 1 -%}
            <td>
                <li><p>
                    <b>{{ book.title_desc }}</b>
                    <br>作者：[{{ book.author.state }}] {{ book.author.name }}
                </p></li>
                <p>
                    <img src="{{ book.imagePath }}" alt="图片加载失败" height="200" width="200"
                         onerror="this.src='/static/images/imgFailed.jpeg'"/>
                    <br>读书笔记：
                    {%- if book.mdNotePath -%}
                        <a href="{{ url_for('main.book_detail', year_id=activeYear.year, book_id=book.id) }}" target="_blank">{{ book.title }}</a>
                    {%- else -%}
                        <font color="#8A8A8A">{{ book.title }}</font>
                    {%- endif -%}
                    <br>推荐指数：{%- for i in range(book.rating) -%}&hearts;{%- endfor -%}
                    <br>完成日期：
                    {%- if activeYear.year == 9999 -%}
                        <font color="#8A8A8A">Reading</font>
                    {%- else -%}
                        {{ book.finish_date }}
                    {%- endif -%}
                    <br><i class="fa fa-thumbs-o-up" aria-hidden="true"> <font style="font-style: normal; color: #E94F06;">{{ book.likes }}</font> 赞</i>
                    {%- if book.eBookPath -%}<a href="{{ book.eBookPath }}" target="_blank" style="margin-left: 5px;">eBook</a>{%- endif -%}
                    {%- if book.one_sentence -%}<br>· {{ book.one_sentence }}{%- endif -%}
                    {%- if session.get('username') and authority == "Root" -%}
                    <div>
                        <div style="float: left;">
                            <form action="{{ url_for('main.edit_book', year_id=book.year_id, book_id=book.id) }}" method="GET">
                                <button type="submit" class="btn-success">编辑</button>
                            </form>
                        </div>
                        <div style="float: left; margin-left: 10px;">
{#                            <!--<form action="{{ url_for('main.del_poetry', cat_id=catid_local, poetry_id=poetry.id) }}" method="POST">-->#}
                            <form action="" method="POST">
                                <button type="submit" class="btn-danger" onclick="return confirm('确认删除文档吗？（该操作不可撤回）')">删除</button>
                            </form>
                        </div>
                        <div style="float: left; margin-left: 10px;">
{#                            <!--<form action="{{ url_for('main.del_poetry', cat_id=catid_local, poetry_id=poetry.id) }}" method="POST">-->#}
                            <form action="" method="POST">
                                <button type="submit" class="btn-default">隐藏</button>
                            </form>
                        </div>
                    </div>
                    {%- endif -%}
                </p>
                <br><div style="margin-top: 20px;"> </div><br>
            </td>
            {%- endif -%}
            {%- if loop.index0 % 4 == 3 -%}
            </tr>
            {%- endif -%}
            {%- if loop.index0 == books|length - 1 -%}
                {%- for td in range(plusTDNum) -%}
                <td></td>
                {%- endfor -%}
                </tr>
            {%- endif -%}
        {%- endfor -%}
    </table>
</ol>
<hr>
{%- if session.get('username') and authority == "Root" -%}
<div style="text-align: center; padding-bottom: 20px;">
    <form action="{{ url_for('main.create_book', year_id=activeYear.year) }}" method="GET">
        <button type="submit" class="btn btn-success">新增书籍</button>
    </form>
</div>
{%- endif -%}
</div>
{% endblock %}

{% block jsscript %}
    <script src="{{ url_for('static', filename='user-defined/js/reading.js') }}" type="text/javascript"></script>
{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block title %}注册{% endblock %}

{% block content %}
<div class="form-container">
	<h3 style="text-align: center;">注册</h3>
	<form class="form-content" action="" method="POST">
		<div class="form-group required">
			<label for="username" class="star-label">用户名</label>
			<input type="text" id="username" class="form-control" name="username" placeholder="Username">
		</div>
		<div class="form-group required">
			<label for="password1" class="star-label">密码</label>
			<input type="password" id="password1" class="form-control" name="password1" placeholder="Password">
		</div>
		<div class="form-group required">
			<label for="password2" class="star-label">确认密码</label>
			<input type="password" id="password2" class="form-control" name="password2" placeholder="Password">
		</div>
		<div class="form-group">
			<button type="submit" class="btn btn-primary btn-block">注册</button>
		</div>
	</form>
</div>
{% endblock %}

{% block jsscript %}
    <script type="text/javascript">
        var content = document.getElementsByClassName("content")[0];
        content.style.setProperty("width", "800px");
    </script>
{% endblock %}